### PR TITLE
fix: arch check in PreDeployValidation

### LINKED ISSUE #656: Check bundle arch against cluster arch
### Steps to reproduce

Assume my cluster arch is amd64 and I'm deploying from my arm64 Mac. Consider the following:
```yaml
# uds-bundle.yaml
kind: UDSBundle
metadata:
  name: ghcr-test
  description: testing a bundle of pkgs from ghcr
  version: 0.0.1

packages:
  - name: podinfo
    repository: ghcr.io/defenseunicorns/uds-cli/podinfo
    ref: 0.0.1
  - name: nginx
    repository: ghcr.io/defenseunicorns/uds-cli/nginx
    ref: 0.0.1

---
# tasks.yaml
  tasks:
  - name: default
    actions:
      - cmd: ./uds create . -a amd64 --confirm --no-progress
      - task: deploy

  - name: deploy
    actions:
      - cmd: |
          set -x
          ./uds deploy $(ls -tr uds-bundle*.tar.zst | tail -1) --confirm --no-progress

```

### Expected result

When running `uds run` the bundle creates and deploys successfully

### Actual Result

Bundle create works but on deploy we get this error:
```
          ERROR:  Failed to validate bundle: arch arm64 does not match cluster arch, [amd64]
     ERROR:  Failed to run action: command "set -x; ./uds deploy $(ls -tr uds-bundle*.tar.zst | tail ..." timed
             out after 0 seconds
```

It appears that UDS CLI is checking the user's system arch against the cluster arch

### Additional Context
The workaround is to simply add `-a amd64` to the `uds deploy` command, but this behavior is still bad. During deploy we should check the bundle's arch against the cluster's arch

### PR DESCRIPTION
**Pull request by TristanHoladay**
## Description
Fix PreDeployValidation() arch check to look at the bundle arch set at create time.

## Related Issue

Fixes #656 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: src/test/common.go [hunk 1]
```diff
@@ -166,9 +166,9 @@ func (e2e *UDSE2ETest) DownloadZarfInitPkg(t *testing.T, zarfVersion string) {
 }
 
 // CreateZarfPkg creates a Zarf package in the given path
-func (e2e *UDSE2ETest) CreateZarfPkg(t *testing.T, path string, forceCreate bool) {
+func (e2e *UDSE2ETest) CreateZarfPkg(t *testing.T, path string, forceCreate bool, arch string) {
```
Comment (TristanHoladay) [inline src/test/common.go:169]: i originally create a duplicate function with the arch param, but then switched this one to take the param. thoughts?

Comment (TristanHoladay) [reply src/test/common.go]: ended up doing the duplicate func after all to pass the arch as a cli flag to the create command.

File: src/test/e2e/bundle_test.go [hunk 2]
```diff
@@ -624,3 +624,16 @@ func TestInvalidBundle(t *testing.T) {
 	stderr := createLocalError(bundleDir, e2e.Arch)
 	require.Contains(t, stderr, "unknown field")
 }
+
+func TestArchCheck(t *testing.T) {
```
Comment (UncleGedd) [inline src/test/e2e/bundle_test.go:628]: This test passes on my arm64 Mac, may need a bit more logic to ensure we're setting the proper arch depending on the system on which this test runs

Comment (TristanHoladay) [reply src/test/e2e/bundle_test.go:628]: mmm, yeah i wondered if something like that was going to happen. Thanks @UncleGedd i'll fix it.

Comment (TristanHoladay) [reply src/test/e2e/bundle_test.go:628]: interesting i saw that too in a previous CI run, but couldn't figure out where it was coming from so i re-ran the job and it went away.

**Review by UncleGedd — APPROVED** [review]
