### PR TITLE
fix: refactor without dependencies on ZarfPackageOptions and ZarfInitOptions structs

### LINKED ISSUE #1243: Incoming Zarf SDK changes in v0.64.0
### Describe what should be investigated or refactored

As a part of https://github.com/zarf-dev/zarf/pull/4235 we removed a few structs that are being used in uds-cli. Specifically `ZarfInitOptions`, `ZarfPackageOptions`. These were used in Zarf only to carry information from cobra commands. The simplest solution would likely be creating more specific structs to carry along the information that's needed.

Happy to help or take any feedback in what Zarf could expose to improve the UX of working with it.

### PR DESCRIPTION
**Pull request by emoskito**
## Description
Removed dependencies/references to `ZarfInitOptions` and `ZarfPackageOptions` structs from the Zarf SDK. These structs, along with others, are being removed in the upcoming Zarf SDK changes in V0.64.0.
...

## Related Issue

Fixes #1243

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: src/pkg/bundle/deploy_test.go [hunk 1]
```diff
@@ -16,7 +16,7 @@ import (
 	"github.com/stretchr/testify/require"
 	"github.com/zarf-dev/zarf/src/api/v1alpha1"
 	"github.com/zarf-dev/zarf/src/pkg/state"
-	zarfTypes "github.com/zarf-dev/zarf/src/types"
+	zarfState "github.com/zarf-dev/zarf/src/pkg/state"
```
Comment (YrrepNoj) [inline src/pkg/bundle/deploy_test.go]: This is now imported twice. We should remove the unnamed import and refactor any references to it.

**Review by YrrepNoj — APPROVED** [review]
