### PR TITLE
fix: refactors tests and fixes bugs

### LINKED ISSUE #449: Make e2e tests easier to read
Currently, our e2e tests give us a ton of confidence, but they are getting harder to reason about. Let's consider making these tests smaller
- Break up large e2e tests
- Create a bundle once test it in smaller tests
- Prefer `path` to `repository` in new tests

### PR DESCRIPTION
**Pull request by UncleGedd**
## Description
Refactors tests and fixes a few bugs
- fix: ensure `make` shows all targets
- fix: ensure the `remove --packages` flow works for local and remote packages
- fix: ensure `--tmpdir` works for local bundles with local and remote packages
- add unit test for variable precedence
- prefer local packages over remote in tests where possible

## Related Issue

Fixes #449

### CODE REVIEW

File: src/test/e2e/bundle_test.go [hunk 1]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
-	// remove customtmp folder if it exists
-	err := os.RemoveAll("./customtmp")
-	require.NoError(t, err)
-
 }
 
 func TestPackagesFlag(t *testing.T) {
 	deployZarfInit(t)
-
-	e2e.CreateZarfPkg(t, "src/test/packages/nginx", false)
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:133]: removed since nginx is the remote package being tested from ghcr

File: src/test/e2e/bundle_test.go [hunk 2]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
-	deployments, _, _ = e2e.UDS(cmd...)
-	require.NotContains(t, deployments, "podinfo")
-	require.NotContains(t, deployments, "nginx")
 
-	// Test invalid package deploy
-	_, stderr := deployPackagesFlag(bundlePath, "podinfo,nginx,peanuts")
-	require.Contains(t, stderr, "invalid zarf packages specified by --packages")
+	t.Run("Test only podinfo deploy (local pkg)", func(t *testing.T) {
+		deployPackagesFlag(bundlePath, "podinfo")
+		cmd := strings.Split("zarf tools kubectl get deployments -A -o=jsonpath='{.items[*].metadata.name}'", " ")
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:132]: this cmd can get moved up since it doesn't get changed and gets used by other tests in this function

File: src/test/e2e/bundle_test.go [hunk 3]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
+		deployments, _, _ := e2e.UDS(cmd...)
+		require.Contains(t, deployments, "podinfo")
+		require.NotContains(t, deployments, "nginx")
+		remove(t, bundlePath)
+	})
 
-	// Test invalid package remove
-	_, stderr = removePackagesFlag(bundlePath, "podinfo,nginx,peanuts")
-	require.Contains(t, stderr, "invalid zarf packages specified by --packages")
+	cmd := strings.Split("zarf tools kubectl get deployments -A -o=jsonpath='{.items[*].metadata.name}'", " ")
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:139]: based on previous comment, this can get deleted now

File: src/test/e2e/bundle_test.go [hunk 4]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
+
+	t.Run("Test both podinfo and nginx deploy", func(t *testing.T) {
+		deployPackagesFlag(bundlePath, "podinfo,nginx")
+		deployments, _, _ := e2e.UDS(cmd...)
+		require.Contains(t, deployments, "podinfo")
+		require.Contains(t, deployments, "nginx")
+
+	})
+	t.Run("Remove only podinfo (local pkg)", func(t *testing.T) {
+		removePackagesFlag(bundlePath, "podinfo")
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:156]: should we deploy the packages again or make sure that they are deployed before trying to run this test. (removing dependencies from previous test that does the deployment)

File: src/test/e2e/bundle_test.go [hunk 5]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
+		deployments, _, _ := e2e.UDS(cmd...)
+		require.NotContains(t, deployments, "podinfo")
+		require.Contains(t, deployments, "nginx")
+
+	})
+	t.Run("Remove only nginx (remote pkg)", func(t *testing.T) {
+		removePackagesFlag(bundlePath, "nginx")
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:163]: should we deploy the packages again or make sure that they are deployed before trying to run this test. (removing dependencies from previous test that does the deployment)

File: src/test/e2e/bundle_test.go [hunk 6]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
+		_, stderr := removePackagesFlag(bundlePath, "podinfo,nginx,peanuts")
+		require.Contains(t, stderr, "invalid zarf packages specified by --packages")
+
+	})
 }
 
 func TestResumeFlag(t *testing.T) {
 	deployZarfInit(t)
-
 	e2e.CreateZarfPkg(t, "src/test/packages/nginx", false)
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:183]: can probably delete since bundle is getting package from ghcr

File: src/test/e2e/bundle_test.go [hunk 7]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
+		require.Contains(t, deployments, "nginx")
+	})
 
 	// Remove only podinfo
-	removePackagesFlag(bundlePath, "podinfo")
-	deployments, _, _ = e2e.UDS(cmd...)
-	require.NotContains(t, deployments, "podinfo")
-	require.Contains(t, deployments, "nginx")
+	t.Run("Remove only podinfo", func(t *testing.T) {
+		removePackagesFlag(bundlePath, "podinfo")
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:212]: make sure packages are deployed for test independence?

File: src/test/e2e/bundle_test.go [hunk 8]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
+		deployments, _, _ := e2e.UDS(getDeploymentsCmd...)
+		require.NotContains(t, deployments, "podinfo")
+		require.Contains(t, deployments, "nginx")
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:215]: "clean up" removing all packages, so later tests are starting with "fresh" env

File: src/test/e2e/bundle_test.go [hunk 9]
```diff
@@ -108,138 +110,143 @@ func TestBundle(t *testing.T) {
...
+	t.Run("Deploy bundle --resume", func(t *testing.T) {
+		deployResumeFlag(t, bundlePath)
+		deployments, _, _ := e2e.UDS(getDeploymentsCmd...)
+		require.Contains(t, deployments, "podinfo")
+		require.Contains(t, deployments, "nginx")
+	})
+
+	// Remove only nginx
+	t.Run("Remove only podinfo", func(t *testing.T) {
+		removePackagesFlag(bundlePath, "nginx")
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:236]: same thing, making sure packages are all deployed

File: src/test/e2e/bundle_test.go [hunk 10]
```diff
@@ -301,24 +306,12 @@ func TestBundleWithYmlFile(t *testing.T) {
 	e2e.CreateZarfPkg(t, "src/test/packages/nginx", true)
 	e2e.CreateZarfPkg(t, "src/test/packages/podinfo", true)
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:307]: can delete, doesnt look like the 09-bundle uses podinfo

File: src/test/e2e/bundle_test.go [hunk 11]
```diff
@@ -491,25 +484,14 @@ func TestBundleTmpDir(t *testing.T) {
 	e2e.CreateZarfPkg(t, "src/test/packages/nginx", false)
```
Comment (decleaver) [inline src/test/e2e/bundle_test.go:484]: can delete, remote nginx from ghcr being used

**Review by decleaver — APPROVED** [review]
comments have been addressed
