### PR TITLE
fix: cli docs

### LINKED ISSUE #793: Fix links in docs
### Description
As identified by our docs pipelines, we have some bad URLs in our docs
Screenshot 2024-07-15 at 8 04 42 AM

### PR DESCRIPTION
**Pull request by decleaver**
## Description

Fix links, fix schema page title, remove powershell refs

## Related Issue

Fixes #793 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: src/cmd/completion.go [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+// Package cmd contains the CLI commands for UDS.
+package cmd
+
+import (
+	"os"
+
+	"github.com/defenseunicorns/uds-cli/src/config/lang"
+	"github.com/spf13/cobra"
+)
+
```
Comment (UncleGedd) [inline src/cmd/completion.go:13]:
```suggestion

// We manually create the completion cmds because autogen'ing the docs includes Powershell completions,
// which we don't support. Cobra doesn't provide a neat mechanism for excluding just Powershell so if we want
// these completion cmds built into the CLI we have to create them manually
```

Comment (UncleGedd) [reply src/cmd/completion.go:13]: ^ this may not come out right if you hit "commit suggestion", might want to copy/paste as you see fit into your branch

**Review by UncleGedd — APPROVED** [review]
